// Auto-generado 2026-07-11 — TIPSTER PRO IA
window.PICKS_DATA = {
  "fecha": "2026-07-11",
  "fecha_display": "Sábado 11 de Julio 2026",
  "generado_a": "automatico-github-actions",
  "nota_lineas": "Cuota de consenso (mediana entre casas). Probabilidad ANCLADA al mercado sharp (Pinnacle) — la IA no inventa favoritos. La cuota mínima es el precio que tu casa (PlayDoIt/Winpot) debe superar. 10 picks con EV+. Horario CDT CDMX.",
  "bankroll": {
    "exposicion_total": "2.05u",
    "max_por_juego": "0.3u",
    "nota": "Kelly 1/4"
  },
  "picks": [
    {
      "liga": "MLB",
      "matchup": "Milwaukee Brewers @ Pittsburgh Pirates",
      "hora": "3:06 PM CDT (CDMX)",
      "pick": "Milwaukee Brewers Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 2.02,
      "prob_implicita": 49.5,
      "prob_propia": 55.5,
      "ev_pct": 12.1,
      "prob_acierto": 58,
      "estrellas": 4,
      "stake": "0.25u",
      "razonamiento": "Brewers son el mejor equipo del contexto (59-34) con un récord visitante excelente 30-16. Drohan (4-2, 2.97 ERA) enfrenta a Chandler (3-8, 4.82 ERA). La ventaja del pitcher es clara: ~1.85 de diferencia en ERA. Pittsburgh está en .500 (47-47) con local 24-24. El mercado en el juego de tarde ofrece 1.86 para Milwaukee, que implica 53.8% — ligeramente infravalorado dado el diferencial de abridores y el récord global.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 58.0,
      "prob_justa": null,
      "fair_source": null,
      "cuota_minima": 1.8
    },
    {
      "liga": "MLB",
      "matchup": "New York Yankees @ Washington Nationals",
      "hora": "3:05 PM CDT (CDMX)",
      "pick": "New York Yankees Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.54,
      "prob_implicita": 64.9,
      "prob_propia": 67.0,
      "ev_pct": 3.2,
      "prob_acierto": 67,
      "estrellas": 4,
      "stake": "0.25u",
      "razonamiento": "Schlittler (9-5, 2.01 ERA) es uno de los abridores más dominantes del contexto, frente a Mikolas (3-7, 5.78 ERA) — diferencial de ERA de 3.77. Yankees 52-42, visitante 29-22 vs Nacionales 48-47 local 20-29. El récord local de Washington es negativo (20-29), lo que refuerza la ventaja de NY. A 1.55 hay valor marginal pero defendible con datos sólidos.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 67.0,
      "prob_justa": 64.0,
      "fair_source": "pinnacle",
      "cuota_minima": 1.49
    },
    {
      "liga": "MLB",
      "matchup": "Los Angeles Angels @ Minnesota Twins",
      "hora": "1:10 PM CDT (CDMX)",
      "pick": "Minnesota Twins Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.6,
      "prob_implicita": 62.5,
      "prob_propia": 65.1,
      "ev_pct": 4.2,
      "prob_acierto": 66,
      "estrellas": 3,
      "stake": "0.20u",
      "razonamiento": "Joe Ryan (6-5, 2.85 ERA) tiene una ventaja enorme sobre Ryan Johnson (1-4, 6.99 ERA) — diferencial de ERA de 4.14, uno de los mayores del día. Angels son 38-57 con visitante 17-32, uno de los peores récords del contexto. La cuota 1.58 implica 63.3%; estimo ~66% dado el matchup de abridores y el mal registro visitante de LA.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 66.0,
      "prob_justa": 60.1,
      "fair_source": "pinnacle",
      "cuota_minima": 1.54
    },
    {
      "liga": "MLB",
      "matchup": "Arizona Diamondbacks @ Los Angeles Dodgers",
      "hora": "8:10 PM CDT (CDMX)",
      "pick": "Los Angeles Dodgers Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.4,
      "prob_implicita": 71.4,
      "prob_propia": 73.0,
      "ev_pct": 2.2,
      "prob_acierto": 73,
      "estrellas": 3,
      "stake": "0.15u",
      "razonamiento": "Yamamoto (9-5, 2.49 ERA) vs Pfaadt (2-1, 4.84 ERA). Dodgers son el mejor récord del contexto (61-34), local 31-17. Aunque la cuota 1.39 es baja, el matchup es muy favorable: mejor equipo de la liga con uno de los mejores abridores. EV modesto pero respaldado por datos concretos. Stake reducido por la cuota baja.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 73.0,
      "prob_justa": 71.3,
      "fair_source": "pinnacle",
      "cuota_minima": 1.37
    },
    {
      "liga": "MLB",
      "matchup": "Atlanta Braves @ St. Louis Cardinals",
      "hora": "6:15 PM CDT (CDMX)",
      "pick": "Atlanta Braves Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.88,
      "prob_implicita": 53.2,
      "prob_propia": 57.0,
      "ev_pct": 7.2,
      "prob_acierto": 57,
      "estrellas": 3,
      "stake": "0.20u",
      "razonamiento": "Braves (54-39, visitante 27-21) con López (4-1, 3.18 ERA) vs Liberatore (4-6, 5.34 ERA). Diferencial de ERA de 2.16 puntos. Atlanta tiene mejor récord global y visitante sólido; Cardinals están en .527 pero local 25-25. A 1.89 el mercado no está penalizando suficiente la ventaja del abridor de Atlanta.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 57.0,
      "prob_justa": 52.0,
      "fair_source": "pinnacle",
      "cuota_minima": 1.75
    },
    {
      "liga": "MLB",
      "matchup": "Philadelphia Phillies @ Detroit Tigers",
      "hora": "5:10 PM CDT (CDMX)",
      "pick": "Philadelphia Phillies Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.83,
      "prob_implicita": 54.6,
      "prob_propia": 57.0,
      "ev_pct": 4.3,
      "prob_acierto": 57,
      "estrellas": 3,
      "stake": "0.20u",
      "razonamiento": "Sánchez (10-4, 2.62 ERA) es uno de los abridores elite del contexto con récord 10-4. Phillies 52-43, visitante 27-22. Mize tiene ERA similar (2.64) pero récord 4-5. La ventaja real está en el récord de Sánchez (10-4 vs 4-5) y el récord global del equipo. EV modesto a 1.83.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 57.0,
      "prob_justa": 53.3,
      "fair_source": "pinnacle",
      "cuota_minima": 1.75
    },
    {
      "liga": "MLB",
      "matchup": "Seattle Mariners @ Tampa Bay Rays",
      "hora": "3:10 PM CDT (CDMX)",
      "pick": "Tampa Bay Rays Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.91,
      "prob_implicita": 52.4,
      "prob_propia": 55.6,
      "ev_pct": 6.2,
      "prob_acierto": 56,
      "estrellas": 3,
      "stake": "0.20u",
      "razonamiento": "Rays (55-37, local 34-14) tienen el mejor récord local del contexto — 34-14 en casa es excepcional. Griffin Jax (4-6, 3.60 ERA) vs Logan Gilbert (7-5, 3.19 ERA) están equiparados en ERA, pero Tampa's local dominance es la ventaja clave. Mariners son 47-48 con visitante 20-28. A 1.91 el mercado no refleja adecuadamente la fortaleza local de Tampa.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 56.0,
      "prob_justa": 50.6,
      "fair_source": "pinnacle",
      "cuota_minima": 1.8
    },
    {
      "liga": "MLB",
      "matchup": "Chicago Cubs @ Cincinnati Reds",
      "hora": "6:10 PM CDT (CDMX)",
      "pick": "Under 10.5 Carreras",
      "tipo": "Total",
      "cuota_bet365": 1.92,
      "prob_implicita": 52.1,
      "prob_propia": 54.1,
      "ev_pct": 3.9,
      "prob_acierto": 58,
      "estrellas": 3,
      "stake": "0.20u",
      "razonamiento": "La línea de 10.5 es muy alta para un juego de béisbol. Assad (6-1, 4.15 ERA) y Lodolo (3-2, 4.68 ERA) son abridores competentes que limitarían scoring extremo. Cubs 52-42, Reds 43-50. El total de 10.5 requiere un juego de altísimo scoring; estimo que ambos lanzadores controlan suficiente para quedarse bajo esa marca la mayoría del tiempo.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 58.0,
      "prob_justa": 49.1,
      "fair_source": "pinnacle",
      "cuota_minima": 1.85
    },
    {
      "liga": "MLB",
      "matchup": "Cleveland Guardians @ Miami Marlins",
      "hora": "3:10 PM CDT (CDMX)",
      "pick": "Miami Marlins Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.71,
      "prob_implicita": 58.5,
      "prob_propia": 60.0,
      "ev_pct": 2.6,
      "prob_acierto": 60,
      "estrellas": 3,
      "stake": "0.15u",
      "razonamiento": "Marlins (52-43, local 31-18) tienen récord local fuerte. Eury Pérez (5-6, 3.84 ERA) vs Bibee (2-9, 4.06 ERA) — ERAs similares pero Bibee con 9 derrotas es un indicador preocupante. Guardians visitante 25-24, decente pero no superior. Marlins en casa con ligera ventaja de pitcher y local 31-18 justifica el pick a 1.73.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 60.0,
      "prob_justa": 57.4,
      "fair_source": "pinnacle",
      "cuota_minima": 1.67
    },
    {
      "liga": "Tennis WTA",
      "matchup": "Linda Noskova @ Karolina Muchova",
      "hora": "9:00 AM CDT (CDMX)",
      "pick": "Karolina Muchova Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.78,
      "prob_implicita": 56.2,
      "prob_propia": 58.7,
      "ev_pct": 4.5,
      "prob_acierto": 59,
      "estrellas": 3,
      "stake": "0.15u",
      "razonamiento": "Muchova es una jugadora de mayor experiencia en torneos grandes y superficie dura. Aunque el contexto no provee estadísticas detalladas de forma reciente, la cuota de 1.78 para Muchova frente a Noskova (2.18) refleja una ligera infravaloración del estilo técnico de Muchova. EV de ~4.9% a 1.78 con estimación conservadora de 59% de probabilidad propia.",
      "sport_key": "tennis_wta_wimbledon",
      "cuota_verificada": true,
      "prob_ia_cruda": 59.0,
      "prob_justa": 53.7,
      "fair_source": "pinnacle",
      "cuota_minima": 1.7
    }
  ],
  "no_apostar": [
    {
      "matchup": "Milwaukee Brewers @ Pittsburgh Pirates (11:05 AM CDT)",
      "liga": "MLB",
      "razon": "Pitchers TBD para ambos equipos — imposible analizar el matchup de abridores que es el factor principal en béisbol."
    },
    {
      "matchup": "Boston Red Sox @ New York Mets",
      "liga": "MLB",
      "razon": "Pitcher visitante TBD (Boston) — sin información del abridor local no se puede evaluar el matchup correctamente."
    },
    {
      "matchup": "Athletics @ Chicago White Sox",
      "liga": "MLB",
      "razon": "Partido muy parejo (1.94 / 1.98), ambos equipos mediocres. No hay ventaja clara: Athletics 41-53, WhiteSox 48-45. Sin edge identificable que justifique el riesgo dado el historial de MLB (-5.7% ROI)."
    },
    {
      "matchup": "Kansas City Royals @ Baltimore Orioles",
      "liga": "MLB",
      "razon": "Royals 38-57 con visitante 17-31 sugiere valor en Baltimore, pero Cameron (4.77 ERA) vs Bradish (3.75 ERA) es un matchup modesto y Orioles con récord global 44-51 también es flojo. Riesgo-recompensa insuficiente."
    },
    {
      "matchup": "Houston Astros @ Texas Rangers",
      "liga": "MLB",
      "razon": "Partido muy parejo (2.02 / 1.90). Lambert (7-5, 3.26) es ligeramente mejor que Rocker (2-7, 3.95) pero los récords de equipo son similares. Sin edge claro para justificar apuesta."
    },
    {
      "matchup": "Colorado Rockies @ San Francisco Giants",
      "liga": "MLB",
      "razon": "Ambos equipos mediocres (39-57 / 39-55) y ambos abridores con ERA alta (Freeland 7.46, Mahle 5.70). Partido impredecible entre dos equipos malos — no apostar."
    },
    {
      "matchup": "Toronto Blue Jays @ San Diego Padres",
      "liga": "MLB",
      "razon": "Yesavage (3.31 ERA) es mejor que Buehler (5.07 ERA) pero los récords globales son casi idénticos (45-49 vs 46-48). La cuota de Toronto a 2.07 podría tener valor pero el contexto de visitante 21-24 para Toronto limita la confianza."
    }
  ],
  "parlay_sugerido": {
    "patas": [
      "Milwaukee Brewers ML (1.86)",
      "New York Yankees ML (1.55)",
      "Minnesota Twins ML (1.58)"
    ],
    "cuota_total": 4.54,
    "ev_pct": 6.8,
    "stake": "0.15u",
    "nota": "Tres picks de alta convicción con ventaja de pitcher clara en cada uno. Brewers-Drohan vs Chandler, Yankees-Schlittler vs Mikolas, Twins-Ryan vs Johnson. Correlación positiva en que los tres favorecen al equipo con mejor abridor y mejor récord global. Cuota combinada de ~4.54."
  },
  "resumen_ejecutivo": [
    {
      "pick": "Milwaukee Brewers ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.86,
      "ev_pct": 7.9,
      "stake": "0.25u",
      "estrellas": 4
    },
    {
      "pick": "New York Yankees ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.55,
      "ev_pct": 3.9,
      "stake": "0.25u",
      "estrellas": 4
    },
    {
      "pick": "Minnesota Twins ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.58,
      "ev_pct": 4.3,
      "stake": "0.20u",
      "estrellas": 3
    },
    {
      "pick": "Los Angeles Dodgers ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.39,
      "ev_pct": 1.5,
      "stake": "0.15u",
      "estrellas": 3
    },
    {
      "pick": "Atlanta Braves ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.89,
      "ev_pct": 7.7,
      "stake": "0.20u",
      "estrellas": 3
    },
    {
      "pick": "Philadelphia Phillies ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.83,
      "ev_pct": 4.3,
      "stake": "0.20u",
      "estrellas": 3
    },
    {
      "pick": "Tampa Bay Rays ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.91,
      "ev_pct": 6.9,
      "stake": "0.20u",
      "estrellas": 3
    },
    {
      "pick": "Cubs @ Reds Under 10.5",
      "tipo": "Total",
      "liga": "MLB",
      "cuota": 1.86,
      "ev_pct": 7.9,
      "stake": "0.20u",
      "estrellas": 3
    },
    {
      "pick": "Miami Marlins ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.73,
      "ev_pct": 3.8,
      "stake": "0.15u",
      "estrellas": 3
    },
    {
      "pick": "Karolina Muchova ML",
      "tipo": "Moneyline",
      "liga": "Tennis WTA",
      "cuota": 1.78,
      "ev_pct": 4.9,
      "stake": "0.15u",
      "estrellas": 3
    }
  ]
};
