// Auto-generado 2026-08-24 — TIPSTER PRO IA
window.PICKS_DATA = {
  "fecha": "2026-08-24",
  "fecha_display": "Lunes 24 de Agosto 2026",
  "generado_a": "automatico-github-actions",
  "nota_lineas": "Cuota de consenso (mediana entre casas). Probabilidad ANCLADA al mercado sharp (Pinnacle) — la IA no inventa favoritos. La cuota mínima es el precio que tu casa (PlayDoIt/Winpot) debe superar. 10 picks con EV+. Horario CDT CDMX.",
  "bankroll": {
    "exposicion_total": "2.15u",
    "max_por_juego": "0.3u",
    "nota": "Kelly 1/4"
  },
  "picks": [
    {
      "liga": "Serie A - Italy",
      "matchup": "Fiorentina @ AS Roma",
      "hora": "1:45 PM CDT (CDMX)",
      "pick": "AS Roma Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.75,
      "prob_implicita": 57.1,
      "prob_propia": 60.4,
      "ev_pct": 5.7,
      "prob_acierto": 61,
      "estrellas": 4,
      "stake": "0.25u",
      "razonamiento": "AS Roma llega con forma WWWWW (5 victorias consecutivas), lo que representa el mejor registro de forma del contexto. Fiorentina muestra forma WDWDL, con derrota en el último partido. AS Roma como local a 1.77 parece ligero valor dado ese momentum brutal. El mercado implica ~56.5%, pero la racha de 5W seguidas justifica estimarlos ~61%. EV de ~8%.",
      "sport_key": "soccer_italy_serie_a",
      "cuota_verificada": true,
      "prob_ia_cruda": 61.0,
      "prob_justa": 55.4,
      "fair_source": "pinnacle",
      "cuota_minima": 1.66,
      "logo_away": "https://a.espncdn.com/i/teamlogos/soccer/500/109.png",
      "logo_home": "https://a.espncdn.com/i/teamlogos/soccer/500/104.png"
    },
    {
      "liga": "EPL",
      "matchup": "Chelsea @ Fulham",
      "hora": "2:00 PM CDT (CDMX)",
      "pick": "Chelsea Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.88,
      "prob_implicita": 53.2,
      "prob_propia": 55.6,
      "ev_pct": 4.5,
      "prob_acierto": 56,
      "estrellas": 3,
      "stake": "0.2u",
      "razonamiento": "Chelsea visita a Fulham. Aunque ambos equipos están al inicio de temporada (0-0-0), la diferencia de calidad de plantilla entre Chelsea y Fulham históricamente es significativa. Fulham muestra forma reciente WDLLW (2 derrotas en últimos 5), Chelsea LWLDL. La cuota de 1.95 para Chelsea visitante ofrece valor dado el gap de calidad entre estos equipos. La cuota de Fulham (4.16) confirma que el mercado favorece claramente a Chelsea.",
      "sport_key": "soccer_epl",
      "cuota_verificada": true,
      "prob_ia_cruda": 56.0,
      "prob_justa": 50.6,
      "fair_source": "pinnacle",
      "cuota_minima": 1.8,
      "logo_away": "https://a.espncdn.com/i/teamlogos/soccer/500/363.png",
      "logo_home": "https://a.espncdn.com/i/teamlogos/soccer/500/370.png"
    },
    {
      "liga": "La Liga - Spain",
      "matchup": "Levante @ CA Osasuna",
      "hora": "12:30 PM CDT (CDMX)",
      "pick": "CA Osasuna Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.88,
      "prob_implicita": 53.2,
      "prob_propia": 55.7,
      "ev_pct": 4.7,
      "prob_acierto": 57,
      "estrellas": 3,
      "stake": "0.2u",
      "razonamiento": "Osasuna juega de local y el mercado la favorece claramente (cuota 1.92 vs 4.57 de Levante). Osasuna como local con la ventaja de campo en La Liga y forma reciente LLLLL para Osasuna es preocupante, pero Levante solo ha jugado 1 partido (0-0-1). La asimetría de cuotas sugiere que el mercado ve a Osasuna como favorito sólido en casa. Con cuota 1.92, prob implícita 52.1%, estimamos 57% dado el advantage local y el nivel de ambos equipos en La Liga.",
      "sport_key": "soccer_spain_la_liga",
      "cuota_verificada": true,
      "prob_ia_cruda": 57.0,
      "prob_justa": 50.7,
      "fair_source": "pinnacle",
      "cuota_minima": 1.8,
      "logo_away": "https://a.espncdn.com/i/teamlogos/soccer/500/1538.png",
      "logo_home": "https://a.espncdn.com/i/teamlogos/soccer/500/97.png"
    },
    {
      "liga": "Primera División - Argentina",
      "matchup": "Rosario Central @ Talleres",
      "hora": "7:15 PM CDT (CDMX)",
      "pick": "Rosario Central Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 2.8,
      "prob_implicita": 35.7,
      "prob_propia": 36.9,
      "ev_pct": 3.3,
      "prob_acierto": 38,
      "estrellas": 3,
      "stake": "0.2u",
      "razonamiento": "Rosario Central llega con forma LWDWW (3 victorias en últimas 3 jornadas, récord 3-1-1). Talleres muestra forma LLWLL con solo 1 victoria en 5 partidos (1-0-4). El mercado trata este juego como equilibrado (2.96 vs 2.77), pero la disparidad de forma es notable. Rosario Central está en momento positivo mientras Talleres ha perdido 4 de 5. A 2.96, el EV es atractivo para el equipo en mejor forma.",
      "sport_key": "soccer_argentina_primera_division",
      "cuota_verificada": true,
      "prob_ia_cruda": 38.0,
      "prob_justa": 31.9,
      "fair_source": "pinnacle",
      "cuota_minima": 2.71,
      "logo_away": "https://a.espncdn.com/i/teamlogos/soccer/500/17.png",
      "logo_home": "https://a.espncdn.com/i/teamlogos/soccer/500/19.png"
    },
    {
      "liga": "Primera División - Argentina",
      "matchup": "Central Córdoba @ CA Tigre BA",
      "hora": "5:00 PM CDT (CDMX)",
      "pick": "Over 1.5 Goles",
      "tipo": "Total Goles",
      "cuota_bet365": 1.99,
      "prob_implicita": 50.3,
      "prob_propia": 53.8,
      "ev_pct": 7.1,
      "prob_acierto": 72,
      "estrellas": 3,
      "stake": "0.2u",
      "razonamiento": "Tigre (2-2-1) es un equipo ofensivo que tiende a participar en partidos con goles. El mercado paga 1.54 para Over 1.5, lo que implica ~65%. En fútbol argentino, los juegos tienden a ser abiertos y el nivel defensivo de ambos equipos (Central Córdoba 2-0-3, Tigre 2-2-1) sugiere que superar 1.5 goles es altamente probable. Estimamos ~72% de probabilidad.",
      "sport_key": "soccer_argentina_primera_division",
      "cuota_verificada": true,
      "prob_ia_cruda": 72.0,
      "prob_justa": 48.8,
      "fair_source": "pinnacle",
      "cuota_minima": 1.86,
      "logo_away": "https://a.espncdn.com/i/teamlogos/soccer/500/11989.png",
      "logo_home": "https://a.espncdn.com/i/teamlogos/soccer/500/7767.png"
    },
    {
      "liga": "Tennis WTA",
      "matchup": "Donna Vekic @ Diane Parry",
      "hora": "10:00 PM CDT (CDMX)",
      "pick": "Donna Vekic Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.62,
      "prob_implicita": 61.7,
      "prob_propia": 64.3,
      "ev_pct": 4.2,
      "prob_acierto": 67,
      "estrellas": 4,
      "stake": "0.25u",
      "razonamiento": "Donna Vekic es tenista de élite WTA con ranking significativamente superior a Diane Parry. La cuota de 1.63 implica 61.3%, pero considerando el diferencial de calidad entre ambas jugadoras, estimamos que Vekic tiene ~67% de chances. Parry no ha mostrado ser una rival consistente en este nivel. La cuota ofrece valor defendible.",
      "sport_key": "tennis_wta_monterrey_open",
      "cuota_verificada": true,
      "prob_ia_cruda": 67.0,
      "prob_justa": 59.3,
      "fair_source": "pinnacle",
      "cuota_minima": 1.56,
      "photo_away": "https://a.espncdn.com/i/headshots/tennis/players/full/2040.png"
    },
    {
      "liga": "Tennis WTA",
      "matchup": "Renata Zarazua @ Clara Tauson",
      "hora": "8:30 PM CDT (CDMX)",
      "pick": "Clara Tauson Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.3,
      "prob_implicita": 76.9,
      "prob_propia": 78.7,
      "ev_pct": 2.3,
      "prob_acierto": 79,
      "estrellas": 3,
      "stake": "0.15u",
      "razonamiento": "Clara Tauson es claramente favorita (1.32) frente a Zarazua (3.38), lo que implica que el mercado ya la posiciona como ganadora en ~76% de los casos. Tauson tiene un nivel WTA muy superior a Zarazua. Con cuota 1.32 el EV es modesto (~4.3%) pero el pick es defensivamente sólido. Stake bajo por cuota reducida.",
      "sport_key": "tennis_wta_monterrey_open",
      "cuota_verificada": true,
      "prob_ia_cruda": 79.0,
      "prob_justa": 73.7,
      "fair_source": "pinnacle",
      "cuota_minima": 1.27
    },
    {
      "liga": "MLB",
      "matchup": "Cincinnati Reds @ San Francisco Giants",
      "hora": "8:45 PM CDT (CDMX)",
      "pick": "Cincinnati Reds Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.66,
      "prob_implicita": 60.2,
      "prob_propia": 64.5,
      "ev_pct": 7.1,
      "prob_acierto": 66,
      "estrellas": 4,
      "stake": "0.25u",
      "razonamiento": "Chase Burns (14-2, ERA 2.51) es uno de los mejores abridores del contexto — récord excepcional y ERA élite. San Francisco tiene abridor TBD (no confirmado), lo que añade incertidumbre al lado local. Giants están 52-78 con ERA del abridor confirmado ausente; Carson Whisenhunt tenía ERA 7.03 en el contexto de la sección. Reds visitantes a 1.66 con Burns en el montículo representa ventaja clara. El mercado implica 60.2%, pero Burns al 14-2/2.51 justifica ~66%.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 66.0,
      "prob_justa": 59.5,
      "fair_source": "pinnacle",
      "cuota_minima": 1.55
    },
    {
      "liga": "MLB",
      "matchup": "Tampa Bay Rays @ Detroit Tigers",
      "hora": "5:40 PM CDT (CDMX)",
      "pick": "Tampa Bay Rays Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.79,
      "prob_implicita": 55.9,
      "prob_propia": 59.8,
      "ev_pct": 7.0,
      "prob_acierto": 61,
      "estrellas": 3,
      "stake": "0.2u",
      "razonamiento": "Rays (77-53) es el equipo con mejor récord en el contexto MLB. Drew Rasmussen (13-5, ERA 3.01) tiene mucho mejor rendimiento que Framber Valdez (8-8, ERA 4.35) de Detroit. Tigers están 61-69 y su abridor tiene ERA 1.34 puntos superior. A 1.78, el mercado da prob implícita de 56.2%, pero la combinación de mejor récord global + abridor superior justifica ~61%.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 61.0,
      "prob_justa": 54.8,
      "fair_source": "pinnacle",
      "cuota_minima": 1.67
    },
    {
      "liga": "MLB",
      "matchup": "Philadelphia Phillies @ Seattle Mariners",
      "hora": "8:40 PM CDT (CDMX)",
      "pick": "Philadelphia Phillies Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.91,
      "prob_implicita": 52.4,
      "prob_propia": 56.4,
      "ev_pct": 7.7,
      "prob_acierto": 57,
      "estrellas": 3,
      "stake": "0.2u",
      "razonamiento": "Zack Wheeler (10-4, ERA 2.92) es claramente superior a Logan Gilbert (10-7, ERA 3.35) como abridor. Phillies están 73-58 (sólido) vs Mariners 62-69. El Total de 6.5 (el más bajo del contexto MLB) refleja que ambos pitchers son buenos, pero Wheeler tiene edge claro. A 1.90, prob implícita 52.6% vs estimada 57%. Mercado casi correcto pero Wheeler da el edge suficiente.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 57.0,
      "prob_justa": 51.4,
      "fair_source": "pinnacle",
      "cuota_minima": 1.77
    }
  ],
  "no_apostar": [
    {
      "matchup": "Colorado Rockies @ Washington Nationals",
      "liga": "MLB",
      "razon": "Rockies son los peores del contexto (50-80) y Feltner tiene ERA 5.97, pero la cuota de Washington (1.56) ya incorpora ese edge. No hay valor adicional claro."
    },
    {
      "matchup": "Texas Rangers @ Chicago White Sox",
      "liga": "MLB",
      "razon": "White Sox TBD como abridor genera incertidumbre. Rocker tiene ERA 4.46 y Rangers están 65-66. Sin ventaja clara identificable."
    },
    {
      "matchup": "Atletico Paranaense @ Botafogo",
      "liga": "Brazil Série A",
      "razon": "Sin estadísticas ESPN disponibles en el contexto para este partido. Insuficiente información para calcular prob_propia confiable."
    },
    {
      "matchup": "Argentinos Juniors @ Lanus",
      "liga": "Primera División - Argentina",
      "razon": "Sin estadísticas ESPN en el contexto. Cuotas casi idénticas (2.93/2.71/2.93) sugieren incertidumbre del mercado. Sin datos suficientes."
    },
    {
      "matchup": "Casa Pia @ Gil Vicente",
      "liga": "Primeira Liga - Portugal",
      "razon": "Casa Pia 0-0-2 muy débil, pero la cuota de Gil Vicente (1.75) ya lo refleja completamente. Margen del mercado Pinnacle es estrecho y no hay edge claro."
    },
    {
      "matchup": "Lazio @ Bologna",
      "liga": "Serie A - Italy",
      "razon": "Lazio con forma LWLLL (4 derrotas en 5), pero el mercado ya la pone como outsider (3.48). Bologna a 2.34 como local ya descuenta esa ventaja. Sin edge claro."
    },
    {
      "matchup": "Ann Li @ Maria Camila Osorio Serrano",
      "liga": "Tennis WTA",
      "razon": "Cuotas casi parejas (1.97 vs 1.82). Sin datos de forma o ranking disponibles en el contexto para diferenciar. Mercado muy equilibrado."
    },
    {
      "matchup": "Minnesota Twins @ Athletics",
      "liga": "MLB",
      "razon": "Ambos equipos por debajo de .500, abridores con ERA elevadas (Matthews 5.12, Springs 6.02). El total de 10.5 es altísimo pero ya está descontado en cuotas. No entra en cupo de 3 picks MLB."
    }
  ],
  "parlay_sugerido": {
    "patas": [
      "AS Roma Moneyline (1.77)",
      "Cincinnati Reds Moneyline (1.66)",
      "Donna Vekic Moneyline (1.63)"
    ],
    "cuota_total": 4.8,
    "ev_pct": 14.2,
    "stake": "0.15u",
    "nota": "Correlación positiva en términos de picks 'forma/calidad del pitcher': Roma en racha perfecta 5W, Burns dominante 14-2/ERA 2.51 vs abridor rival sin confirmar, y Vekic con ventaja clara de ranking. Los tres picks tienen EV individual positivo y estimaciones independientes. Cuota total atractiva con riesgo acotado."
  },
  "resumen_ejecutivo": [
    {
      "pick": "AS Roma Moneyline",
      "tipo": "Moneyline",
      "liga": "Serie A - Italy",
      "cuota": 1.77,
      "ev_pct": 8.0,
      "stake": "0.25u",
      "estrellas": 4
    },
    {
      "pick": "Cincinnati Reds Moneyline",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.66,
      "ev_pct": 9.6,
      "stake": "0.25u",
      "estrellas": 4
    },
    {
      "pick": "Donna Vekic Moneyline",
      "tipo": "Moneyline",
      "liga": "Tennis WTA",
      "cuota": 1.63,
      "ev_pct": 9.2,
      "stake": "0.25u",
      "estrellas": 4
    },
    {
      "pick": "Chelsea Moneyline",
      "tipo": "Moneyline",
      "liga": "EPL",
      "cuota": 1.95,
      "ev_pct": 9.2,
      "stake": "0.2u",
      "estrellas": 3
    },
    {
      "pick": "CA Osasuna Moneyline",
      "tipo": "Moneyline",
      "liga": "La Liga - Spain",
      "cuota": 1.92,
      "ev_pct": 9.4,
      "stake": "0.2u",
      "estrellas": 3
    },
    {
      "pick": "Rosario Central Moneyline",
      "tipo": "Moneyline",
      "liga": "Primera División - Argentina",
      "cuota": 2.96,
      "ev_pct": 12.5,
      "stake": "0.2u",
      "estrellas": 3
    },
    {
      "pick": "Over 1.5 Goles (Central Córdoba @ Tigre)",
      "tipo": "Total Goles",
      "liga": "Primera División - Argentina",
      "cuota": 1.54,
      "ev_pct": 10.9,
      "stake": "0.2u",
      "estrellas": 3
    },
    {
      "pick": "Tampa Bay Rays Moneyline",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.78,
      "ev_pct": 8.6,
      "stake": "0.2u",
      "estrellas": 3
    },
    {
      "pick": "Philadelphia Phillies Moneyline",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.9,
      "ev_pct": 8.3,
      "stake": "0.2u",
      "estrellas": 3
    },
    {
      "pick": "Clara Tauson Moneyline",
      "tipo": "Moneyline",
      "liga": "Tennis WTA",
      "cuota": 1.32,
      "ev_pct": 4.3,
      "stake": "0.15u",
      "estrellas": 3
    }
  ]
};
