// Auto-generado 2026-07-21 — TIPSTER PRO IA
window.PICKS_DATA = {
  "fecha": "2026-07-21",
  "fecha_display": "Martes 21 de Julio 2026",
  "generado_a": "automatico-github-actions",
  "nota_lineas": "Cuota de consenso (mediana entre casas). Probabilidad ANCLADA al mercado sharp (Pinnacle) — la IA no inventa favoritos. La cuota mínima es el precio que tu casa (PlayDoIt/Winpot) debe superar. 10 picks con EV+. Horario CDT CDMX.",
  "bankroll": {
    "exposicion_total": "2.05u",
    "max_por_juego": "0.3u",
    "nota": "Kelly 1/4"
  },
  "picks": [
    {
      "liga": "MLB",
      "matchup": "Los Angeles Dodgers @ Philadelphia Phillies",
      "hora": "5:41 PM CDT (CDMX)",
      "pick": "Philadelphia Phillies Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.77,
      "prob_implicita": 56.5,
      "prob_propia": 60.4,
      "ev_pct": 6.9,
      "prob_acierto": 61,
      "estrellas": 4,
      "stake": "0.25u",
      "razonamiento": "Zack Wheeler lleva marca 10-1 con ERA 2.13, una de las mejores temporadas de cualquier abridor en la liga. El contexto muestra al abridor visitante como Eric Lauer (4-5, ERA 4.81), no Justin Wrobleski. Phillies 56-45 en casa 27-23 vs Dodgers visitantes 32-19; la diferencia de ERA entre abridores es enorme (~2.68 puntos). Prob implícita 56.5%, mi estimación ajustada 61% da EV positivo claro y bien respaldado.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 61.0,
      "prob_justa": 55.4,
      "fair_source": "pinnacle",
      "cuota_minima": 1.66
    },
    {
      "liga": "MLB",
      "matchup": "Tampa Bay Rays @ Toronto Blue Jays",
      "hora": "6:08 PM CDT (CDMX)",
      "pick": "Tampa Bay Rays Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.92,
      "prob_implicita": 52.1,
      "prob_propia": 56.4,
      "ev_pct": 8.3,
      "prob_acierto": 57,
      "estrellas": 4,
      "stake": "0.25u",
      "razonamiento": "Rays 57-42 (récord superior), Drew Rasmussen 7-5 ERA 3.26 supera a Kevin Gausman 4-8 ERA 4.33. Toronto local 25-28, récord general 46-54. El mercado tiene el juego prácticamente a 50/50, pero Tampa tiene mejor récord, mejor abridor y su rival en casa tiene récord negativo. Ajuste calibrado: +4.9 pts sobre prob implícita.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 57.0,
      "prob_justa": 51.4,
      "fair_source": "pinnacle",
      "cuota_minima": 1.77
    },
    {
      "liga": "MLB",
      "matchup": "San Diego Padres @ Atlanta Braves",
      "hora": "6:16 PM CDT (CDMX)",
      "pick": "Atlanta Braves Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.73,
      "prob_implicita": 57.8,
      "prob_propia": 61.2,
      "ev_pct": 5.9,
      "prob_acierto": 62,
      "estrellas": 3,
      "stake": "0.25u",
      "razonamiento": "Braves 58-41 con récord local espectacular 30-19. Reynaldo López 4-2 ERA 3.50 vs Walker Buehler 5-5 ERA 5.36 (ventaja de ~1.86 ERA puntos). Padres visitantes 22-27, récord general 49-51. Matchup favorable en todas las dimensiones: récord, abridor, local/visitante.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 62.0,
      "prob_justa": 56.2,
      "fair_source": "pinnacle",
      "cuota_minima": 1.63
    },
    {
      "liga": "MLB",
      "matchup": "Cincinnati Reds @ Seattle Mariners",
      "hora": "8:41 PM CDT (CDMX)",
      "pick": "Cincinnati Reds Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.97,
      "prob_implicita": 50.8,
      "prob_propia": 54.1,
      "ev_pct": 6.6,
      "prob_acierto": 55,
      "estrellas": 4,
      "stake": "0.25u",
      "razonamiento": "Chase Burns es el abridor más dominante del contexto: 11-1 ERA 2.54 — marca élite. Luis Castillo contra 3-8 ERA 4.93 del lado local. El mercado casi iguala el juego (1.99 vs 1.93) ignorando esta diferencia de calidad en el montículo. Mariners 51-50 locales 30-21 pero Castillo está en temporada muy pobre. Burns justifica un ajuste de ~4.7 pts de ventaja.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 55.0,
      "prob_justa": 49.1,
      "fair_source": "pinnacle",
      "cuota_minima": 1.85
    },
    {
      "liga": "MLB",
      "matchup": "Washington Nationals @ Colorado Rockies",
      "hora": "7:41 PM CDT (CDMX)",
      "pick": "Over 12.5 Total Carreras",
      "tipo": "Total",
      "cuota_bet365": 1.94,
      "prob_implicita": 51.5,
      "prob_propia": 54.6,
      "ev_pct": 5.9,
      "prob_acierto": 58,
      "estrellas": 3,
      "stake": "0.2u",
      "razonamiento": "Miles Mikolas 3-7 ERA 5.53 vs Michael Lorenzen 3-9 ERA 6.22 — ambos abridores entre los peores del contexto. Coors Field amplifica la ofensa considerablemente (altitud). La línea de 12.5 ya es alta pero con estos abridores y este estadio el Over tiene valor real. Ambas bullpens tendrán presión temprana.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 58.0,
      "prob_justa": 49.6,
      "fair_source": "pinnacle",
      "cuota_minima": 1.83
    },
    {
      "liga": "MLB",
      "matchup": "Minnesota Twins @ Cleveland Guardians",
      "hora": "5:41 PM CDT (CDMX)",
      "pick": "Cleveland Guardians Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.69,
      "prob_implicita": 59.2,
      "prob_propia": 61.0,
      "ev_pct": 3.1,
      "prob_acierto": 61,
      "estrellas": 3,
      "stake": "0.2u",
      "razonamiento": "Parker Messick 8-5 ERA 2.73 vs Kendry Rojas 1-1 ERA 2.79 — abridores parejos en ERA pero Messick con mucha más experiencia y victorias. Guardians 53-48 récord superior a Twins 49-52. Local 26-24 vs visitantes 23-27. Ventaja ligera de ~3 puntos justificada por récord y solidez del abridor.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 61.0,
      "prob_justa": null,
      "fair_source": null,
      "cuota_minima": 1.64
    },
    {
      "liga": "MLB",
      "matchup": "Miami Marlins @ Houston Astros",
      "hora": "7:11 PM CDT (CDMX)",
      "pick": "Miami Marlins Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 2.02,
      "prob_implicita": 49.5,
      "prob_propia": 52.2,
      "ev_pct": 5.4,
      "prob_acierto": 53,
      "estrellas": 3,
      "stake": "0.2u",
      "razonamiento": "Tatsuya Imai local tiene ERA 6.06 — uno de los más altos del contexto hoy. Tyler Phillips visitante 2-4 ERA 3.48, diferencia de 2.58 ERA puntos a favor de Marlins. Astros 48-54 récord negativo, local 24-27 también negativo. El mercado da a Houston como favorito basado en historia pero los datos de hoy favorecen a Miami. Marlins 52-49 en mejor forma.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 53.0,
      "prob_justa": 47.2,
      "fair_source": "pinnacle",
      "cuota_minima": 1.92
    },
    {
      "liga": "MLB",
      "matchup": "New York Mets @ Milwaukee Brewers",
      "hora": "6:41 PM CDT (CDMX)",
      "pick": "Milwaukee Brewers Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.73,
      "prob_implicita": 57.8,
      "prob_propia": 61.0,
      "ev_pct": 5.5,
      "prob_acierto": 61,
      "estrellas": 3,
      "stake": "0.2u",
      "razonamiento": "Brewers 63-37 el mejor récord del contexto hoy, local 33-18 sobresaliente. Mets 42-59 visitantes 21-31 — uno de los peores registros del día. Aunque Sproat tiene ERA 5.16, el respaldo ofensivo y bullpen de Milwaukee vs un Mets debilitado justifica confiar en el local. Zac Thornton del NY apenas con 1 decisión como visitante.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 61.0,
      "prob_justa": 56.8,
      "fair_source": "pinnacle",
      "cuota_minima": 1.64
    },
    {
      "liga": "MLB",
      "matchup": "Athletics @ Arizona Diamondbacks",
      "hora": "8:41 PM CDT (CDMX)",
      "pick": "Arizona Diamondbacks Moneyline",
      "tipo": "Moneyline",
      "cuota_bet365": 1.77,
      "prob_implicita": 56.5,
      "prob_propia": 60.0,
      "ev_pct": 6.2,
      "prob_acierto": 60,
      "estrellas": 3,
      "stake": "0.2u",
      "razonamiento": "Jack Perkins 2-5 ERA 6.87 es el abridor con peor ERA del contexto hoy. Diamondbacks 51-49 local 29-22 récord favorable. Athletics 43-57 visitantes 23-27. La diferencia de calidad en el abridor es clara y el mercado a 1.80 ofrece valor real dado que ARI tiene local 29-22 y el rival trae el pitcher más castigado del día.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 60.0,
      "prob_justa": null,
      "fair_source": null,
      "cuota_minima": 1.67
    },
    {
      "liga": "MLB",
      "matchup": "Cincinnati Reds @ Seattle Mariners",
      "hora": "8:41 PM CDT (CDMX)",
      "pick": "Under 7.5 Total Carreras",
      "tipo": "Total",
      "cuota_bet365": 1.93,
      "prob_implicita": 51.8,
      "prob_propia": 55.0,
      "ev_pct": 6.2,
      "prob_acierto": 55,
      "estrellas": 3,
      "stake": "0.15u",
      "razonamiento": "Chase Burns 11-1 ERA 2.54 es un abridor dominante que suprime carreras. La línea de 7.5 es baja pero Burns tiene capacidad para mantener el marcador bajo en los primeros innings. Castillo pese a su mala temporada debería recibir apoyo del bullpen de Seattle. Combinación de ambos abridores justifica Under en línea baja de 7.5.",
      "sport_key": "baseball_mlb",
      "cuota_verificada": true,
      "prob_ia_cruda": 55.0,
      "prob_justa": 50.4,
      "fair_source": "pinnacle",
      "cuota_minima": 1.82
    }
  ],
  "no_apostar": [
    {
      "matchup": "Pittsburgh Pirates @ New York Yankees",
      "liga": "MLB",
      "razon": "Will Warren 7-4 ERA 4.03 vs Bubba Chandler 3-8 ERA 4.77; línea justa, sin ventaja clara identificable más allá del precio."
    },
    {
      "matchup": "Baltimore Orioles @ Boston Red Sox",
      "liga": "MLB",
      "razon": "Ambos equipos con récords negativos o mediocres; abridores con ERA muy similar (3.61 vs 3.15); sin edge claro."
    },
    {
      "matchup": "San Francisco Giants @ Kansas City Royals",
      "liga": "MLB",
      "razon": "Ambos equipos con récords muy malos y abridores con ERA altas (5.31 vs 5.08); mercado casi a precio justo, alto ruido."
    },
    {
      "matchup": "Detroit Tigers @ Chicago Cubs",
      "liga": "MLB",
      "razon": "David Peterson ERA 6.45 favorece Detroit pero Framber Valdez 5-6 ERA 4.10 no está en su mejor nivel; señales mixtas."
    },
    {
      "matchup": "Chicago White Sox @ Texas Rangers",
      "liga": "MLB",
      "razon": "Ambos abridores con ERA elevados (5.60 vs 4.40); mercado equilibrado, dificultad para identificar edge real."
    },
    {
      "matchup": "St. Louis Cardinals @ Los Angeles Angels",
      "liga": "MLB",
      "razon": "Walbert Ureña ERA 2.88 sorprendente para un equipo 40-61; situación confusa de línea; Angels récord muy malo pero abridor en buena forma relativa."
    }
  ],
  "parlay_sugerido": {
    "patas": [
      "Philadelphia Phillies ML (1.77)",
      "Atlanta Braves ML (1.73)",
      "Cincinnati Reds ML (1.99)"
    ],
    "cuota_total": 6.09,
    "ev_pct": 8.4,
    "stake": "0.1u",
    "nota": "Tres picks independientes con el mejor EV del día basados en diferencial de ERA de abridor y récord. Wheeler, López y Burns son los tres mejores abridores en sus juegos respectivos con diferencias significativas frente a sus rivales."
  },
  "resumen_ejecutivo": [
    {
      "pick": "Cincinnati Reds ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.99,
      "ev_pct": 9.45,
      "stake": "0.25u",
      "estrellas": 4
    },
    {
      "pick": "Tampa Bay Rays ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.92,
      "ev_pct": 9.44,
      "stake": "0.25u",
      "estrellas": 4
    },
    {
      "pick": "Philadelphia Phillies ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.77,
      "ev_pct": 7.97,
      "stake": "0.25u",
      "estrellas": 4
    },
    {
      "pick": "Miami Marlins ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 2.12,
      "ev_pct": 12.36,
      "stake": "0.2u",
      "estrellas": 3
    },
    {
      "pick": "Arizona Diamondbacks ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.8,
      "ev_pct": 8.0,
      "stake": "0.2u",
      "estrellas": 3
    },
    {
      "pick": "Atlanta Braves ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.73,
      "ev_pct": 7.26,
      "stake": "0.25u",
      "estrellas": 3
    },
    {
      "pick": "Over 12.5 — Washington Nationals @ Colorado Rockies",
      "tipo": "Total",
      "liga": "MLB",
      "cuota": 1.85,
      "ev_pct": 7.3,
      "stake": "0.2u",
      "estrellas": 3
    },
    {
      "pick": "Milwaukee Brewers ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.73,
      "ev_pct": 5.53,
      "stake": "0.2u",
      "estrellas": 3
    },
    {
      "pick": "Cleveland Guardians ML",
      "tipo": "Moneyline",
      "liga": "MLB",
      "cuota": 1.72,
      "ev_pct": 4.92,
      "stake": "0.2u",
      "estrellas": 3
    },
    {
      "pick": "Under 7.5 — Cincinnati Reds @ Seattle Mariners",
      "tipo": "Total",
      "liga": "MLB",
      "cuota": 1.95,
      "ev_pct": 7.25,
      "stake": "0.15u",
      "estrellas": 3
    }
  ]
};
